### PR TITLE
Fix comparison operator bug, and implement minimum working example.

### PR DESCRIPTION
**Pull request by jsharkey13**
Implement a fix for the comparison operator bug, alongside implementing a bare-bones working example and very brief instructions on how to use.

### CODE REVIEW

**Comment by jsharkey13** [comment]
Ah - I've written a bunch of stuff loosely based on your code; I forked the repository mainly to give you some of the credit for the original ideas. The scientific Python install I've been using in my degree is 2.7, and I plan to stick to that. I think our ideas diverge, so I shan't be submitting any more pull requests - I just had to fix that little bug to get it working correctly and thought since I'd fixed it for you I'd make it easy for you to use it.

**I think I'll close this pull request**, but you should just fix the three bits which were broken in your original code (which were 79-86 of `fb_chat.py`; did you mean 21-24 of `fb_parser.py` were the ones I broke?) . I only meant the first commit to be included in the request, but apparently that's not how GitHub sees things (I should have submitted a pull request from another branch) . . .
My code is only loosely based on yours - if you'd rather I made a new repository so that you didn't have my branch; let me know how to credit you, and I'll do that.

As for the str(...) conversion; if you do anything other than dump to JSON, things still go horribly wrong. I had great difficulty getting Python to play nicely with the Unicode nature of BeautifulSoup's strings and  part of my fix was an ugly hack to set Python's default encoding to unicode for only one file:

``` python
reload(sys)
sys.setdefaultencoding('utf8')
```

which definitely isn't good practice! I couldn't get the code to run using `str(...)` conversion, which is why I got rid of it; but replacing it with `unicode(...)` seems to allow pickling and avoid the error you get without the conversion.

**Comment by CopOnTheRun** [comment]
> did you mean 21-24 of fb_parser.py were the ones I broke?

Whoopsie, yes those were the lines I meant.

> As for the str(...) conversion; if you do anything other than dump to JSON, things still go horribly wrong. I had great difficulty getting Python to play nicely with the Unicode nature of BeautifulSoup's strings and part of my fix was an ugly hack to set Python's default encoding to unicode for only one file

Ah yes, that probably has to do with the fact that we're using different versions of python. I believe python 3.X's default encoding is utf-8 to begin with which would explain why `str(...)` worked for me but not yourself.

**Comment by jsharkey13** [comment]
That makes sense - you might just want to make sure that it works fine in Python 3 still! It'd be handy if it worked in both!

**Comment by CopOnTheRun** [comment]
No that would be too easy. Oh well, everything is fixed now!

**Pull request closed without merging**
