### PR TITLE
PEP 8

### PR DESCRIPTION
**Pull request by sinwoobang**
Hi, there.
I try to improve the code by applying PEP 8.

Thanks.

### CODE REVIEW

**Comment by CopOnTheRun** [comment]
Thank you very much! I started this as a personal project to learn python, and just used github to host my code. I didn't think anyone would actually be looking at the code, but I guess that's not the case. I'll merge your suggestions now!

**Comment by sinwoobang** [comment]
Haha :+1:

**Comment by ervinpython** [comment]
Hi, I'm interested to try your code but i do not know how. May i ask for instructions? I do not know python or what :) I'm interested in getting information from facebook's messages.htm to get old messages haha

Thank You

**Comment by sinwoobang** [comment]
@ervinpython Hi :)
By the way, It did not contribute to make this code.
I just tried to improve this code.

You must go to @CopOnTheRun to obtain the help.

**Comment by CopOnTheRun** [comment]
Hey @ervinpython I was actually thinking about updating the README.md to provide some basic instructions as to how to use the program. Also I may make a command line interface because I want to practice with the `argparse` module, but that may have to wait for a bit. I'll see if I can update the README.md with instructions this weekend or so. If you wish to continue conversation on this topic, please start a [new issue](https://github.com/CopOnTheRun/FB-Message-Parser/issues) as this thread has diverged from its original purpose. Thanks! :)

**Pull request merged**
